name: Trigger - Main - Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      environment: 'prod'
  
  deploy:
    needs: [build]
    uses: ./.github/workflows/_deploy.yml
    with:
      ssh_host: ${{ vars.PROD_SSH_HOST }}
      ssh_user: ${{ vars.PROD_SSH_USER }}
      ssh_current_dir: ${{ vars.PROD_SERVER_CURRENT_VERSION_DIR }}
      ssh_versions_dir: ${{ vars.PROD_SERVER_VERSIONS_DIR }}
      ssh_uploadfile_dir: ${{ vars.PROD_SERVER_UPLOADFILE_DIR }}
    secrets:
      SSH_KEY: '${{ secrets.PROD_SSH_KEY }}'