name: '(Shared) Build'

on:
  workflow_call:
    inputs:
      environment:
        description: 'Build Environment'
        required: false
        default: 'prod'
        type: string
      node_version:
        description: 'Node Version'
        required: false
        default: '20.x'
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check Out the Repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'
      - name: List Build Output 1
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Contents of client directory:"
          ls -la client
          echo "Contents of client/dist directory (if it exists):"
          ls -la client/dist || echo "client/dist directory not found"
      - name: Install dependencies
        run: cd client && npm install
      - name: Build Project
        run: cd client && npm run build
      - name: List Build Output 2
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Contents of client directory:"
          ls -la client
          echo "Contents of client/dist directory (if it exists):"
          ls -la client/dist || echo "client/dist directory not found"
      - name: Clean Git Data
        run: rm -rf .git
      - name: Cache Build Files
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ./**/*
          key: ${{ runner.os }}-cache-build-${{ github.run_id }}
      - name: Verify Build Location
        run: |
          echo "Current directory:"
          pwd
          echo "???"
          ./**/*
          echo "Cache key used:"
          echo "${{ runner.os }}-cache-build-${{ github.run_id }}"
