name: Trigger - Main - Push

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      environment: 'production'

  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      SSH_HOST: ${{ vars.SSH_HOST }}
      SSH_USER: ${{ vars.SSH_USER }}
    secrets:
      SSH_PASSWORD: '${{ secrets.SSH_PASSWORD }}'
